routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\WishlistController;
use App\Http\Livewire\Dashboard;
use App\Http\Livewire\Home;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', Home::class)->name('/');
Route::get('list-products/{pages}', 'App\Http\Controllers\ProductController@pages')->name('products.page');

Route::group(['middleware' => ['auth', 'web', 'verified']], function () {
    Route::get('/dashboard', Dashboard::class)->name('dashboard');

    Route::resource('products', ProductController::class);
    Route::resource('wishlists', WishlistController::class);
    Route::post('wishlists/clean', 'App\Http\Controllers\WishlistController@removeAll')->name('wishlists.removeAll');

    Route::resource('users', UsersController::class);
});

app/Models/Wishlist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Wishlist extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'product_id',
    ];


    public function users()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function products()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }
}

app/Http/Controllers/WishlistController.php
<?php

namespace App\Http\Controllers;

use App\Models\Wishlist;
use Illuminate\Http\Request;

class WishlistController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if (auth()->user()->role_id === 1) {
            $wishlists = Wishlist::with('products')->get();
        } else {
            $wishlists = Wishlist::where('user_id', auth()->user()->id)->get();
        }
        return view('wishlists.index', compact('wishlists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $productId = $request->id;

        Wishlist::create([
            'user_id' => auth()->user()->id,
            'product_id' => $productId,
        ]);

        session()->flash('flash.banner', 'Product has been added to wishlist !');
        session()->flash('flash.bannerStyle', 'success');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Wishlist $wishlist)
    {
        return view('wishlists.detail', compact('wishlist'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Wishlist::find($id)->delete();

        session()->flash('flash.banner', 'Product has been remove from wishlist !');
        session()->flash('flash.bannerStyle', 'danger');
        return redirect()->to('wishlists.index');
    }

    public function removeAll(Request $request)
    {
        $tmpWishlist = Wishlist::where('user_id', auth()->user()->id)->get();
        $tmpWishlist->each->delete();

        session()->flash('flash.banner', 'Product has been removed from wishlist !');
        session()->flash('flash.bannerStyle', 'danger');
        return redirect()->back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/wishlists/detail.blade.php
<x-app-layout>

    <section class="bg-white">
        <div class="w-full px-5 py-6 mx-auto space-y-5 sm:py-8 md:py-12 sm:space-y-8 md:space-y-16 max-w-7xl">

            <div class="flex flex-col items-center sm:px-5 md:flex-row">
                <div class="w-full md:w-1/2">
                    <a href="#_" class="block">
                        <img class="object-cover w-full h-full rounded-lg max-h-64 sm:max-h-96"
                            src="{{ asset('storage/' . $wishlist->products->image_url) }}">
                    </a>
                </div>
                <div class="flex flex-col items-start justify-center w-full h-full py-6 mb-6 md:mb-0 md:w-1/2">
                    <div
                        class="flex flex-col items-start justify-center h-full space-y-3 transform md:pl-10 lg:pl-16 md:space-y-5">
                        @if ($wishlist->products->category->id == 1)
                            <div
                                class="bg-purple-500 flex items-center pl-2 pr-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                            @elseif ($wishlist->products->category->id == 2)
                                <div
                                    class="bg-pink-500 flex items-center pl-2 pr-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                                @else
                                    <div
                                        class="bg-blue-500 flex items-center pl-2 pr-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                        @endif
                        <span>{{ $wishlist->products->category->name }}</span>
                    </div>
                    <h1 class="text-4xl font-bold leading-none lg:text-5xl xl:text-6xl"><a
                            href="#_">{{ $wishlist->products->name }}</a></h1>
                    <p class="text-sm text-gray-500">{{ $wishlist->products->description }}.</p>
                    <p class="pt-2 text-xl font-bold font-medium">
                        <span class="mx-1">$ </span>
                        <span class="mx-1 text-gray-600">{{ $wishlist->products->price }}</span>
                    </p>
                    <form action="{{ route('wishlists.destroy', $wishlist->id) }}" method="POST">

                        @csrf
                        @method('delete')
                        <input type="hidden" id="id" name="id" value="{{ $wishlist->products->id }}" />
                        <button type="submit" onclick="return confirm('Are you sure?')"
                            class="flex items-center w-full px-6 py-3 mb-3 text-lg text-white bg-red-600 rounded-md sm:mb-0 hover:bg-red-700 sm:w-auto">
                            Remove wishlist
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 ml-1" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round">
                                <line x1="5" y1="12" x2="19" y2="12"></line>
                                <polyline points="12 5 19 12 12 19"></polyline>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>
        </div>
        </div>
    </section>

    @livewire('footer')

</x-app-layout>

resources/views/wishlists/index.blade.php
<x-app-layout>
    <header class="bg-white shadow">
        <div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    All wishlists ({{ count($wishlists) }})
                </h2>
                <div>
                    @if ($wishlists->isNotEmpty())
                        <form class="inline-block" action="{{ route('wishlists.removeAll') }}" method="POST">
                            @csrf

                            <button type="submit" onclick="return confirm('Are you sure?')"
                                class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 mr-4">
                                Remove all
                            </button>
                        </form>
                    @endif
                </div>
            </div>
        </div>
    </header>
    @if ($wishlists->isEmpty())
        <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
            <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">
                <span class="block">Wishlists is empty!</span>
            </h2>
        </div>
    @else

        <div class="py-12">
            <div class="max-w-2xl mx-auto px-4 sm:px-6 lg:max-w-7xl lg:px-8">
                @can('admin')
                    <div class="flex mt-6 flex-col">
                        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                                    <table class="min-w-full divide-y divide-gray-200">
                                        <thead class="bg-gray-50">
                                            <tr>
                                                <th scope="col"
                                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Username
                                                </th>
                                                <th scope="col"
                                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Product
                                                </th>
                                                <th scope="col"
                                                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Created at
                                                </th>
                                                <th scope="col" class="relative px-6 py-3">
                                                    <span class="sr-only">Edit</span>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody class="bg-white divide-y divide-gray-200">

                                            @foreach ($wishlists as $w)
                                                <tr>
                                                    <td class="px-6 py-4 whitespace-nowrap">
                                                        <div class="flex items-center">
                                                            <div class="flex-shrink-0 h-10 w-10">
                                                                <img class="h-10 w-10 rounded-full"
                                                                    src="{{ $w->users->profile_photo_url }}"
                                                                    alt="{{ $w->users->name }}">
                                                            </div>
                                                            <div class="ml-4">
                                                                <div class="text-sm font-medium text-gray-900">
                                                                    {{ $w->users->name }}</div>
                                                                <div class="text-sm text-gray-500">{{ $w->users->email }}
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td class="px-6 py-4 whitespace-nowrap">
                                                        <div class="text-sm text-gray-900">{{ $w->products->name }}</div>
                                                    </td>
                                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                        <span
                                                            class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                            {{ $w->created_at->format('d M Y') }}
                                                        </span>
                                                    </td>
                                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                                        <a href="{{ route('wishlists.show', $w->id) }}"
                                                            class="text-indigo-600 hover:text-indigo-900">Detail</a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            <!-- More people... -->
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                @else
                    <div class="flex grid grid-cols-12 pb-10 sm:px-5 gap-x-8 gap-y-16">

                        @foreach ($wishlists as $pd)
                            <div class="flex flex-col items-start col-span-12 space-y-3 sm:col-span-6 xl:col-span-4">
                                <a href="{{ route('wishlists.show', $pd->id) }}" class="block">
                                    <img class="object-cover w-full mb-2 overflow-hidden rounded-lg shadow-sm max-h-56"
                                        src="{{ asset('storage/' . $pd->products->image_url) }}">
                                </a>
                                @if ($pd->products->category->id == 1)
                                    <div
                                        class="bg-purple-500 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                                        <span>{{ $pd->products->category->name }}</span>
                                    </div>
                                @elseif($pd->products->category->id == 2)
                                    <div
                                        class="bg-pink-500 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                                        <span>{{ $pd->products->category->name }}</span>
                                    </div>
                                @else
                                    <div
                                        class="bg-blue-500 flex items-center px-3 py-1.5 leading-none rounded-full text-xs font-medium uppercase text-white inline-block">
                                        <span>{{ $pd->products->category->name }}</span>
                                    </div>
                                @endif

                                <h2 class="text-lg font-bold sm:text-xl md:text-2xl"><a
                                        href="{{ route('wishlists.show', $pd->id) }}">{{ $pd->products->name }}</a>
                                </h2>
                                <p class="text-sm text-gray-500">{{ $pd->products->description }}.</p>
                                <p class="pt-2 text-xs font-medium">
                                    <span class="mx-1">$ </span>
                                    <span class="mx-1 text-gray-600">{{ $pd->products->price }}</span>
                                </p>
                            </div>

                        @endforeach
                    </div>
                @endcan
            </div>
        </div>
    @endif
</x-app-layout>